/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package plants;

import java.awt.Dimension;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import javax.swing.JPanel;
import plants.TDA.Lista_Doble;

/**
 *
 * @author Javier
 */
public class crearP extends javax.swing.JInternalFrame {

    /**
     * Creates new form crearP
     */
    public crearP() {
             initComponents();
             btnListo.setEnabled(false);
        jPanel1.setLayout(new GridLayout());
        cargarPanel(jPanel1,p);
    }
    
     Lista_Doble lista=new Lista_Doble();
    Lista_Doble listaP=new Lista_Doble();
    int lugar=0;
    Plantas p=new Plantas();
 String tipoPersonaje="Plantas";
    
    public void modificarPanel()
    {
        panel2.setLayout(new GridBagLayout());
        
    }

    public void setNombres(String nombreUsuario,String tipo)
    {
        this.tipoPersonaje=tipo;
        this.label1.setText("Bienvenido "+nombreUsuario+" crea tus "+tipo);
        p.setTipo(tipo);
        p.cambiarImagen(1);
    }
    
    public void getPersonajes()
    {
        int a=panel2.getComponentCount();
        Plantas ax=new Plantas();
        for(int i=0;i<a;i++)
        {
            ax=(Plantas)panel2.getComponent(i);
            lista.InsertarFinal(ax);
        }
        
    }
    
    
    
    private void cargarPanel(JPanel contenedor, JPanel contenedorHijo)
   {
       // Se definen los tamanos iniciales de cada uno
       final Dimension tamanoJFrameInicial = this.getSize(); // JFrame padre
       final Dimension tamanoContenedorPrincipalInicial = contenedor.getPreferredSize().getSize(); // Contenedor que albergara al otro
       final Dimension tamanoFormularioInicial = contenedorHijo.getPreferredSize().getSize(); // El hijo, el JPanel donde será puesto
 
       // Borramos cualquier cosa que pueda haber en el contenedor padre
       contenedor.removeAll();
 
       // Tamano del contenedor que va a tener a los q se le meta
       Dimension nuevoTamano = new Dimension(tamanoFormularioInicial.width, tamanoFormularioInicial.height); // Le ponemos el tamano de lo que albergara y la altura correspondiente
       contenedor.setPreferredSize(nuevoTamano); // Se le asigna ese nuevo tamaño
 
       // Anadimos al contenedor el JPanel llamado al contenedor y lo ponemos visible (por defecto no son visibles, hay que ponerlos)
       contenedor.add(contenedorHijo).setVisible(true);
 
       this.pack(); // Hacemos esto para que se reestructure el JFrame principal y autoajuste su tamano a lo que contiene dentro
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        btnCargar = new javax.swing.JButton();
        btnListo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(460, 460));
        setPreferredSize(new java.awt.Dimension(552, 531));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label1.setText("Crea tus ");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 490, -1));
        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 9, -1, -1));

        jPanel1.setBackground(new java.awt.Color(88, 41, 41));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 29, 516, -1));

        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 180, 173, -1));

        btnListo.setText("Listo");
        btnListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListoActionPerformed(evt);
            }
        });
        getContentPane().add(btnListo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 155, -1));

        panel2.setBackground(new java.awt.Color(38, 99, 40));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panel2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 222, 526, 268));

        jLabel1.setBackground(new java.awt.Color(0, 153, 0));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 550, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Lista_Doble pp=new Lista_Doble();
    
    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        Plantas nuevoPanel=new Plantas();
        lugar++;
        nuevoPanel.setNuevo(p.Cargar());
        panel2.setLayout(null);
        panel2.setLayout(new GridLayout(lugar,1));
        panel2.add (nuevoPanel);//nuevoPanel,1,contador);
        cargarPanel(jPanel1,p);
        this.btnListo.setEnabled(true);
        this.pack();
        
    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListoActionPerformed
        int a=this.panel2.getComponentCount();
        
        for(int i=0;i<a;i++)
        {
            Plantas ax=(Plantas)this.panel2.getComponent(i);
            ax.Cargar();
            this.lista.InsertarFinal(ax);
        }
    }//GEN-LAST:event_btnListoActionPerformed

    public Lista_Doble getLista()
    {
        if(lista.esVacia())
        {
            System.out.println("esta vacia");
        }
        return this.lista;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnListo;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JPanel panel2;
    // End of variables declaration//GEN-END:variables
}
