/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package plants;

import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import plants.TDA.Lista_Doble;

/**
 *
 * @author Javier
 */
public class items extends javax.swing.JFrame {

    /**
     * Creates new form items
     */
    public items( ) {
        initComponents();
        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        //setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.nombretxt.setText(nombreJugador);
        this.Cant.setText(String.valueOf(cantidad));
        this.lblRespuestaNuevo.setEnabled(false);
        
    }
    String tipo()
    { 
        return (esPlanta)? "Planta":"Zombie"; 
    }
    
    private boolean esPlanta=false;
    void plantas(boolean plantas)
    {
     this.esPlanta=plantas;
     tipotxt.setText(tipo());
    }
    Lista_Doble lista=new Lista_Doble();
    public void llenarLista()
    {
        lista.InsertarFinal(nombreJugador);
        lista.InsertarFinal(cantidad);
        lista.InsertarFinal(tipo());
        
    }
    public Lista_Doble getLista()
    {
        return this.lista;
    }
    
    public Lista_Doble getExtras()
    {
        return this.Extras;
    }
    
    public String getNombre()
    {
        return this.nombreJugador;
    }
    public int getCantidad()
    {
        return this.cantidad;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        nombretxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Cant = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tipotxt = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblNuevoCampo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblRespuestaNuevo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crea tu usuario");
        setBackground(new java.awt.Color(51, 204, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombretxt.setBackground(new java.awt.Color(204, 255, 153));
        nombretxt.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(nombretxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 52, 375, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Cantidad:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        Cant.setBackground(new java.awt.Color(204, 255, 153));
        Cant.setForeground(new java.awt.Color(0, 51, 102));
        Cant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CantKeyTyped(evt);
            }
        });
        getContentPane().add(Cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 83, 375, -1));

        jButton2.setText("Listo!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 216, -1, -1));

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 216, -1, -1));

        tipotxt.setText("Tipo");
        getContentPane().add(tipotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 18, -1, 16));

        jButton1.setText("Extras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 182, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Nuevo extra:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        lblNuevoCampo.setBackground(new java.awt.Color(204, 255, 153));
        lblNuevoCampo.setForeground(new java.awt.Color(0, 51, 102));
        lblNuevoCampo.setText("Ingresa tu Nuevo campo");
        lblNuevoCampo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNuevoCampoMouseClicked(evt);
            }
        });
        getContentPane().add(lblNuevoCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 121, 372, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("Entrada Extra");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        lblRespuestaNuevo.setBackground(new java.awt.Color(204, 255, 153));
        lblRespuestaNuevo.setForeground(new java.awt.Color(0, 51, 102));
        lblRespuestaNuevo.setText("Ingresa tu respuesta");
        lblRespuestaNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRespuestaNuevoMouseClicked(evt);
            }
        });
        getContentPane().add(lblRespuestaNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 156, 369, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plantas-vs-zombies.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(nombretxt.getText().equals("") || Cant.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,  "Campos Vacios", null,JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            cantidad=Integer.valueOf(this.Cant.getText());
            nombreJugador=nombretxt.getText();
            llenarLista();
            this.dispose();
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed
    public void limpiar()
    {
        cantidad=0;
        nombreJugador="";
        this.Extras.vaciar();
    }
    
    
    private void CantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CantKeyTyped
        char car=evt.getKeyChar();
        if((car<'0'||car>'9')) evt.consume();
    }//GEN-LAST:event_CantKeyTyped

    private void lblNuevoCampoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNuevoCampoMouseClicked
        // TODO add your handling code here:
        this.lblNuevoCampo.setText("");
        this.lblRespuestaNuevo.setEnabled(true);
    }//GEN-LAST:event_lblNuevoCampoMouseClicked

    private void lblRespuestaNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRespuestaNuevoMouseClicked
        // TODO add your handling code here:
        this.lblRespuestaNuevo.setText("");
    }//GEN-LAST:event_lblRespuestaNuevoMouseClicked
Lista_Doble Extras=new Lista_Doble();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String temp=new String();
        temp=this.lblNuevoCampo.getText()+": \n"+this.lblRespuestaNuevo.getText();
        Extras.InsertarFinal(temp);
        
    }//GEN-LAST:event_jButton1ActionPerformed
    int cantidad;
    String nombreJugador;
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new items().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cant;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lblNuevoCampo;
    private javax.swing.JTextField lblRespuestaNuevo;
    private javax.swing.JTextField nombretxt;
    private javax.swing.JLabel tipotxt;
    // End of variables declaration//GEN-END:variables
}
