/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package plants;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Javier
 */
public class objeto extends javax.swing.JPanel {

    /**
     * Creates new form objeto
     */
    public objeto() {
        initComponents();
    }
    int img;
    String tipo;
    personaje per=new personaje();
    
    public void setImg(int imagen)
    {
        this.img=imagen;
    }
    
    public void setTipo(String ti)
    {
        this.tipo=ti;
    }
    
    public void setImagen()
    {
        cambiarImagen();
    }
    public void setNombre(String nombre)
    {
        this.lbNombre.setText(nombre);
    }
    
    public void setPersonaje(personaje nuevo,boolean pila)
    {
        setNombre(nuevo.getNombre());
        if(pila)
        {
            setTipo("Plantas");
        }
        else
        {
            setTipo("Zombies");
        }
        this.setImg(nuevo.getImagen());
        
        System.out.println(nuevo.getNombre()+":"+nuevo.getImagen());
        this.img=nuevo.getImagen();
        System.out.println(nuevo.getNombre()+":"+img);
        cambiarImagen();
    }
    
    public String getNombre()
    {
        return this.lbNombre.getText();
    }
    
    
    public void cambiarImagen()
    {
        String path="../imagenes/"+tipo+"/"+String.valueOf(img)+".png";
        //System.out.println(path);
        ImageIcon imgIcon = new ImageIcon(getClass().getResource(path));
        Image imgEscalada = imgIcon.getImage().getScaledInstance(75,75, Image.SCALE_SMOOTH);
        Icon iconoEscalado = new ImageIcon(imgEscalada);
        lbImagen.setIcon(iconoEscalado);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbImagen = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(lbImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 37, 87, 84));

        lbNombre.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lbNombre.setText("Nombre");
        add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 127, -1));

        jLabel1.setBackground(new java.awt.Color(0, 153, 0));
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 120));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbImagen;
    private javax.swing.JLabel lbNombre;
    // End of variables declaration//GEN-END:variables
}
