/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package plants;

import java.awt.GridLayout;
import plants.TDA.Lista_Doble;
import plants.TDA.Pila;

/**
 *
 * @author Javier
 */
public class picola extends javax.swing.JPanel {

    /**
     * Creates new form picola
     */
    int lugar=0;
    public picola() {
        initComponents();
        
    }
    objeto imagen=new objeto();
    Lista_Doble lista=new Lista_Doble();
    Pila p=new Pila();
    Cola c=new Cola();
    boolean pila=false;
    int tamaño=1;
    int control=0;
    
    public void agregar()//Lista_Doble list)
    {
        lugar++;
        this.setLayout(new GridLayout(lugar,1));
        objeto nuevo=new objeto();
        this.add(nuevo);
    }
    public void setLista(Lista_Doble list,boolean Plants,int tam)
    {
        this.pila=Plants;
        this.lista=list;
        this.tamaño=tam;
    }
    
    public void cargarPersonajes()
    {
        Plantas temporal=new Plantas();
        String nombre="";
        int img=1;
        if(pila)
        {
            for(int i=1;i<(tamaño+1);i++)
            {
                this.control=i;
                objeto n=new objeto();
                n.setPersonaje(temporal.getNuevo());
                p.Insertar(n);
            }
            
        }
        else
        {
            
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 99, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
