/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package plants;

import java.awt.GridLayout;
import plants.TDA.Lista_Doble;
import plants.TDA.Pila;
import plants.TDA.cola;

/**
 *
 * @author Javier
 */
public class picola extends javax.swing.JPanel {

    /**
     * Creates new form picola
     */
    int lugar=0;
    public picola() {
        initComponents();
        
    }
    objeto imagen=new objeto();
    Lista_Doble lista=new Lista_Doble();
    Pila p=new Pila();
    cola c=new cola();
    boolean pila=false;
    int tamano=1;
    int control=0;
    
    public void agregar()//Lista_Doble list)
    {
        lugar++;
        this.setLayout(new GridLayout(lugar,1));
        objeto nuevo=new objeto();
        this.add(nuevo);
    }
    public void setLista(Lista_Doble list,boolean Plants,int tam)
    {
        
        this.pila=Plants;
        //System.out.println(pila);
        this.lista=list;
        //System.out.println(lista);
        this.tamano=tam;
        //System.out.println(tam);
    }
    
    public void cargarPersonajes()
    {
        //System.out.println("cargar personajes");
        Plantas temporal=new Plantas();
        String nombre="";
        int img=1;
        this.setLayout(null);
        this.setLayout(new GridLayout(1,tamano));//tamano,1));
        /*objeto n=new objeto();
                n.setPersonaje(temporal.getNuevo(),pila);
                p.Insertar(n);
                this.add(n);
                this.updateUI();*/
                
        System.out.println("cantidad de objetos en la pila"+tamano);
        if(pila)
        {
            for(int i=1;i<(tamano+1);i++)
            {
                this.control=i;
                objeto n=new objeto();
                n.setPersonaje(temporal.getNuevo(),pila);
                p.Insertar(n);
                this.updateUI();
                this.add(n);
            }
            
        }
        else
        {
            for(int i=1;i<(tamano+1);i++)
            {
                this.control=i;
                objeto n=new objeto();
                n.setPersonaje(temporal.getNuevo(),pila);
                n.crear();
                c.insertar(n);
                this.updateUI();
                this.add(n);
            }
        }
                
    }
    
    public void cargar()
    {
        if(pila)
        {
            Pila temporal=new Pila();
            temporal=p;
        }else
        {
            cola temporal=new cola();
            temporal=c;
        }
    }
    
    public void obtenerRandom(Plantas z)
    {
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("pila");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
