/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package plants;

/**
 *
 * @author Javier
 */
public class Plantas extends javax.swing.JPanel {

    /**
     * Creates new form Plantas
     */
    public Plantas() {
        initComponents();
        
        
        
    }
    personaje nuevo=new personaje();
    public void setNuevo(personaje nuevop)
    {
        this.nuevo=nuevop;
        setDatos(nuevop);
    }
    public void setDatos(personaje entrada)
    {
        nombrePersonajes.setText(entrada.getNombre());
        numeroAtaque.setText(String.valueOf(entrada.getPuntos()));
        numeroPersonajes.setText(String.valueOf(entrada.getCanitdad()));
        cambiarImagen(entrada.getImagen());
        boolean at=false;
        if(entrada.isAtaqueDirecto())
        {
            rbtnDirecto.setSelected(true);
            rbtnDisparo.setSelected(false);
        }
        else
        {
            rbtnDirecto.setSelected(false);
            rbtnDisparo.setSelected(true);
        }
    }
    public void GuardarDatos()
    {
        nuevo.setAtaqueDirecto(this.rbtnDirecto.isSelected());
        nuevo.setCanitdad(Integer.valueOf(this.numeroPersonajes.getText()));
        nuevo.setNombre(this.nombrePersonajes.getText());
        nuevo.setImagen(imagen);
        nuevo.setPuntos(Integer.valueOf(numeroAtaque.getText()));
    }
    
    public personaje Cargar()
    {
        GuardarDatos();
        return this.nuevo;
    }
    
    //public void
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nombrePersonajes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        numeroAtaque = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rbtnDirecto = new javax.swing.JRadioButton();
        rbtnDisparo = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        numeroPersonajes = new javax.swing.JTextField();

        jButton3.setText("jButton3");

        jLabel1.setText("jLabel1");

        jButton1.setText("<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(">");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        nombrePersonajes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombrePersonajesKeyTyped(evt);
            }
        });

        jLabel3.setText("Puntos:");

        numeroAtaque.setText("10");
        numeroAtaque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroAtaqueKeyTyped(evt);
            }
        });

        jLabel4.setText("Ataque:");

        rbtnDirecto.setText("Directo");
        rbtnDirecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDirectoActionPerformed(evt);
            }
        });

        rbtnDisparo.setText("Disparo");
        rbtnDisparo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDisparoActionPerformed(evt);
            }
        });

        jLabel5.setText("Cantidad de ");

        numeroPersonajes.setText("1");
        numeroPersonajes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroPersonajesKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombrePersonajes))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numeroAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(numeroPersonajes, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnDisparo)
                                    .addComponent(rbtnDirecto))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombrePersonajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)
                        .addComponent(jButton2))
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(rbtnDirecto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnDisparo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addComponent(numeroAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numeroPersonajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void numeroAtaqueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroAtaqueKeyTyped
        char car=evt.getKeyChar();
        if((car<'0'||car>'9')) evt.consume();
    }//GEN-LAST:event_numeroAtaqueKeyTyped

    private void nombrePersonajesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombrePersonajesKeyTyped
        this.jLabel5.setText("Cantidad de "+this.nombrePersonajes.getText());
    }//GEN-LAST:event_nombrePersonajesKeyTyped

    public String Nombre()
    {
        return this.nombrePersonajes.getText();
    }
    
    private void numeroPersonajesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroPersonajesKeyTyped
        char car=evt.getKeyChar();
        if((car<'0'||car>'9')) evt.consume();
    }//GEN-LAST:event_numeroPersonajesKeyTyped

    private void rbtnDirectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDirectoActionPerformed
       /*if (rbtnDirecto.isSelected())
       {
           rbtnDisparo.setSelected(false);
       }
       else
       {*/
           rbtnDirecto.setSelected(true);
           rbtnDisparo.setSelected(false);
       //}
    }//GEN-LAST:event_rbtnDirectoActionPerformed

    private void rbtnDisparoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDisparoActionPerformed
        rbtnDirecto.setSelected(false);
           rbtnDisparo.setSelected(true);
    }//GEN-LAST:event_rbtnDisparoActionPerformed
    int imagen=1;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(this.imagen==1)
        {
            imagen=1;
        }
        else
        {
            imagen--;
        }
       cambiarImagen(imagen);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if(this.imagen==5)
       {
           this.imagen=5;
       }
       else
       {
           this.imagen++;
       }
      cambiarImagen(imagen);        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cambiarImagen(int img)
    {
        
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nombrePersonajes;
    private javax.swing.JTextField numeroAtaque;
    private javax.swing.JTextField numeroPersonajes;
    private javax.swing.JRadioButton rbtnDirecto;
    private javax.swing.JRadioButton rbtnDisparo;
    // End of variables declaration//GEN-END:variables
}
