/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package plants;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Javier
 */
public class Plantas extends javax.swing.JPanel {

    /**
     * Creates new form Plantas
     */
    String tipo="Plantas";
    public Plantas() {
        initComponents();
        cambiarImagen(1);
        rbtnDirecto.setSelected(true);
        
    }
    personaje nuevo=new personaje();
    public void setNuevo(personaje nuevop)
    {
        this.nuevo=nuevop;
        setDatos(nuevop);
    }
    public void setDatos(personaje entrada)
    {
        nombrePersonajes.setText(entrada.getNombre());
        numeroAtaque.setText(String.valueOf(entrada.getPuntos()));
        numeroPersonajes.setText(String.valueOf(entrada.getCanitdad()));
        this.tipo=String.valueOf(entrada.getTipo());
        cambiarImagen(entrada.getImagen());
        setImagen(entrada.getImagen());
        boolean at=false;
        if(entrada.isAtaqueDirecto())
        {
            rbtnDirecto.setSelected(true);
            rbtnDisparo.setSelected(false);
        }
        else
        {
            rbtnDirecto.setSelected(false);
            rbtnDisparo.setSelected(true);
        }
    }
     public personaje getNuevo()
    {
        return this.nuevo;
    }
    
    public void GuardarDatos()
    {
        nuevo= new personaje();
        nuevo.setAtaqueDirecto(this.rbtnDirecto.isSelected());
        nuevo.setCanitdad(Integer.valueOf(this.numeroPersonajes.getText()));
        nuevo.setNombre(this.nombrePersonajes.getText());
        nuevo.setImagen(getImagen());
        nuevo.setPuntos(Integer.valueOf(numeroAtaque.getText()));
        nuevo.setTipo(this.tipo);
    }
    
    public personaje Cargar()
    {
        GuardarDatos();
        return this.nuevo;
    }
    
    //public void
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nombrePersonajes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        numeroAtaque = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rbtnDirecto = new javax.swing.JRadioButton();
        rbtnDisparo = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        numeroPersonajes = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 91, 74));

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setText("<");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 153, 0));
        jButton2.setText(">");
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 62, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        nombrePersonajes.setBackground(new java.awt.Color(204, 255, 153));
        nombrePersonajes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombrePersonajesKeyTyped(evt);
            }
        });
        add(nombrePersonajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 11, 418, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Puntos:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 42, -1, -1));

        numeroAtaque.setBackground(new java.awt.Color(204, 255, 153));
        numeroAtaque.setText("10");
        numeroAtaque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroAtaqueKeyTyped(evt);
            }
        });
        add(numeroAtaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 42, 64, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ataque:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 42, -1, -1));

        rbtnDirecto.setForeground(new java.awt.Color(255, 255, 255));
        rbtnDirecto.setText("Directo");
        rbtnDirecto.setOpaque(false);
        rbtnDirecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDirectoActionPerformed(evt);
            }
        });
        add(rbtnDirecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 64, -1, -1));

        rbtnDisparo.setForeground(new java.awt.Color(255, 255, 255));
        rbtnDisparo.setText("Disparo");
        rbtnDisparo.setOpaque(false);
        rbtnDisparo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDisparoActionPerformed(evt);
            }
        });
        add(rbtnDisparo, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 87, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cantidad de ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 119, 288, -1));

        numeroPersonajes.setBackground(new java.awt.Color(204, 255, 153));
        numeroPersonajes.setText("1");
        numeroPersonajes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroPersonajesKeyTyped(evt);
            }
        });
        add(numeroPersonajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 116, 126, -1));

        jLabel7.setBackground(new java.awt.Color(0, 153, 0));
        jLabel7.setOpaque(true);
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 150));
    }// </editor-fold>//GEN-END:initComponents

    private void numeroAtaqueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroAtaqueKeyTyped
        char car=evt.getKeyChar();
        if((car<'0'||car>'9')) evt.consume();
    }//GEN-LAST:event_numeroAtaqueKeyTyped

    private void nombrePersonajesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombrePersonajesKeyTyped
        this.jLabel5.setText("Cantidad de "+this.nombrePersonajes.getText());
    }//GEN-LAST:event_nombrePersonajesKeyTyped

    public String Nombre()
    {
        return this.nombrePersonajes.getText();
    }
    
    private void numeroPersonajesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroPersonajesKeyTyped
        char car=evt.getKeyChar();
        if((car<'0'||car>'9')) evt.consume();
    }//GEN-LAST:event_numeroPersonajesKeyTyped

    private void rbtnDirectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDirectoActionPerformed
       /*if (rbtnDirecto.isSelected())
       {
           rbtnDisparo.setSelected(false);
       }
       else
       {*/
           rbtnDirecto.setSelected(true);
           rbtnDisparo.setSelected(false);
       //}
    }//GEN-LAST:event_rbtnDirectoActionPerformed

    private void rbtnDisparoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDisparoActionPerformed
        rbtnDirecto.setSelected(false);
           rbtnDisparo.setSelected(true);
    }//GEN-LAST:event_rbtnDisparoActionPerformed
    int imagen=1;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(this.imagen==1)
        {
            this.imagen=1;
        }
        else
        {
            this.imagen--;
        }
       cambiarImagen(imagen);
       //setImagen(imagen);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if(this.imagen==5)
       {
           this.imagen=5;
       }
       else
       {
           this.imagen++;
       }
      cambiarImagen(imagen);      
      //setImagen(imagen);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void cambiarImagen(int img)
    {
        setImagen(img);
        String path="../imagenes/"+tipo+"/"+String.valueOf(img)+".png";
        ImageIcon imgIcon = new ImageIcon(getClass().getResource(path));
        Image imgEscalada = imgIcon.getImage().getScaledInstance(75,75, Image.SCALE_SMOOTH);
        Icon iconoEscalado = new ImageIcon(imgEscalada);
        jLabel1.setIcon(iconoEscalado);
        
    }
    public void setTipo(String ti)
    {
        this.tipo=ti;
    }
    
    public void setImagen(int imagen)
    {
        this.imagen=imagen;
    }
    public int getImagen()
    {
        return this.imagen;
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nombrePersonajes;
    private javax.swing.JTextField numeroAtaque;
    private javax.swing.JTextField numeroPersonajes;
    private javax.swing.JRadioButton rbtnDirecto;
    private javax.swing.JRadioButton rbtnDisparo;
    // End of variables declaration//GEN-END:variables
}
