/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package plants;

import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.JPanel;
import plants.TDA.Lista_Doble;

/**
 *
 * @author Javier
 */
public class table extends javax.swing.JInternalFrame implements Runnable {

    /**
     * Creates new form table
     */
    public table() {
        initComponents();
    }
    picola pila=new picola();
    picola cola=new picola();
    Lista_Doble plantas=new Lista_Doble();
    Lista_Doble zombies=new Lista_Doble();
    Lista_Doble usuarioP=new Lista_Doble();
    Lista_Doble usuarioZ=new Lista_Doble();
    items uplantas=new items();
    items uzombies=new items();
    int cantidadPersonajesPlantas=0;
    int cantidadPersonajesZombies=0;
    public void cargarPaneles()
    {
        crearPaneles();
    }
    
    public void setListas(Lista_Doble plan,Lista_Doble zombie,Lista_Doble up, Lista_Doble uz,items planta,items zombiee)
    {
        this.plantas=plan;
        this.zombies=zombie;
        this.usuarioP=up;
        this.usuarioZ=uz;
        this.uplantas=planta;
        this.uzombies=zombiee;
        this.cantidadPersonajesPlantas=plantas.tamano();
        this.cantidadPersonajesZombies=zombies.tamano();
    }
    

    
    public void crearPaneles()
    {
        pila.setLista(plantas, true,uplantas.cantidad);
        pila.cargarPersonajes();
        this.panelPila.removeAll();
        this.panelPila.add(pila);
        this.panelPila.setLayout(null);
        this.panelPila.setLayout(new GridLayout(1,1));
        this.panelPila.updateUI();
        this.pack();
        
        cola.setLista(zombies, false, uzombies.cantidad);
        cola.cargarPersonajes();
        this.panelCola.removeAll();
        this.panelCola.add(cola);
        this.panelCola.setLayout(null);
        this.panelCola.setLayout(new GridLayout (1,1));
        this.panelCola.updateUI();
        this.pack();
    }
    
    
    
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPlantas = new javax.swing.JScrollPane();
        panelPila = new javax.swing.JPanel();
        scrollZombies = new javax.swing.JScrollPane();
        panelCola = new javax.swing.JPanel();

        setBackground(new java.awt.Color(17, 119, 15));
        setMaximizable(true);
        setResizable(true);
        setTitle("Tablero de Juego");
        setToolTipText("Juega ");
        setOpaque(false);
        setVisible(true);

        javax.swing.GroupLayout panelPilaLayout = new javax.swing.GroupLayout(panelPila);
        panelPila.setLayout(panelPilaLayout);
        panelPilaLayout.setHorizontalGroup(
            panelPilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
        );
        panelPilaLayout.setVerticalGroup(
            panelPilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        scrollPlantas.setViewportView(panelPila);

        javax.swing.GroupLayout panelColaLayout = new javax.swing.GroupLayout(panelCola);
        panelCola.setLayout(panelColaLayout);
        panelColaLayout.setHorizontalGroup(
            panelColaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        panelColaLayout.setVerticalGroup(
            panelColaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        scrollZombies.setViewportView(panelCola);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollPlantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 315, Short.MAX_VALUE)
                .addComponent(scrollZombies, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPlantas)
            .addComponent(scrollZombies)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelCola;
    private javax.swing.JPanel panelPila;
    private javax.swing.JScrollPane scrollPlantas;
    private javax.swing.JScrollPane scrollZombies;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
